apiVersion: v1
kind: Service
metadata: 
  name: order-service
  namespace: coffee-shop
spec: 
  selector:
    app: order-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8083
      nodePort: 30008
  type: NodePort

