apiVersion: v1
kind: Service
metadata: 
  name: inventory-service
  namespace: stage
spec: 
  selector:
    app: inventory-pod
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30007
  type: NodePort

